# Generated by Django 3.2 on 2021-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210501_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=8799907667, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='adi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.IntegerField(default=8890989098),
            preserve_default=False,
        ),
    ]
